### PR TITLE
Feature/hahsu/921130332 boilerplate

### PR DESCRIPTION
**Pull request by hahsu**
### Administrative Info
Monday Board ID: 853628905
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Created the boilerplate code: express backend, react frontend. 

### Testing
How did you confirm your changes worked? 
1. cd into backend folder
2. run the command "npm start"
3. cd into client folder
4. run the command "npm start"
5. Go to browser: http://localhost:3000/ and you should see "Supply Chain" centered.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
Screen Shot 2020-12-19 at 1 33 25 PM

### CODE REVIEW

**Review by justinyaodu — APPROVED** [review]
Looks good to me!

**Review by petabite — APPROVED** [review]
lgtm! A suggestion is we could maybe add [nodemon](https://nodemon.io/) to the backend so we can get auto-reloads on changes if we wanted.

**Review by lynguyxn — APPROVED** [review]
Looks good! Phillip's suggestion about adding nodemon sounds like a nice addition👍

**Comment by hahsu** [comment]
> lgtm! A suggestion is we could maybe add [nodemon](https://nodemon.io/) to the backend so we can get auto-reloads on changes if we wanted.

Thanks for letting me know @petabite! I added it and it should now run nodemon when you use npm start.

**Comment by zainnk902** [comment]
Looks fine!

**Review by AnsonLee99 — APPROVED** [review]
lgtm!

**Review by zainnk902 — APPROVED** [review]

**Review by Benson272 — APPROVED** [review]
LGTM

**Pull request merged**
